# jvm: test.cpp MethodInfo.cpp InterfaceInfo.cpp CpInfo.cpp ClassLoader.cpp ByteReader.cpp AttributeInfo.cpp
# 	g++ -std=c++11 -o jvm test.cpp MethodInfo.cpp InterfaceInfo.cpp CpInfo.cpp ClassLoader.cpp ByteReader.cpp AttributeInfo.cpp -I.

jvm: test.cpp
	g++ -std=c++11 -o jvm test.cpp